# Generated by Django 3.2.7 on 2021-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('freq', models.IntegerField()),
                ('monitor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comps',
            },
        ),
    ]
